name: build-test-deploy
on: [push]
jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the change
        uses: actions/checkout@v4
      - name: Use Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run build
  test:
    needs: [build]
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the change
        uses: actions/checkout@v4
      - name: Use Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
      - run: npm test
  deploy:
    needs: test
    name: Deployment
    permissions: 
      contents: write
      pages: write
      id-token: write
    environment: 
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the change
        uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHB_TOKEN}}
      - name: configure github pages
        uses: actions/configure-pages@v4
      - name: Use Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
